# Generated by Copier from this repo's `template/`. Do not edit by hand.
# See `.copier-answers.yml` for the substitutions; `copier update` regenerates.
"""Google Drive CLI wrapping rclone with manifest-tracked push/pull workflows."""

from __future__ import annotations

__version__ = "0.1.0"
