# Generated by Copier from this repo's `template/`. Do not edit by hand.
# See `.copier-answers.yml` for the substitutions; `copier update` regenerates.
"""Allow running as `python -m gdrive`."""

from __future__ import annotations

from gdrive.cli import cli

cli()
