version: 2

updates:
  # --- GitHub Actions ------------------------------------------------------

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      gh-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
