# Generated by Copier from this repo's `template/`. Do not edit by hand.
# See `.copier-answers.yml` for the substitutions; `copier update` regenerates.
"""Shared CLI helpers used across ga4's subcommand modules."""

from __future__ import annotations

import json
import os
import sys
from typing import Any


def output_json(data: Any) -> None:
    """Write JSON to stdout. `default=str` covers datetimes and protobuf timestamps."""
    json.dump(data, sys.stdout, indent=2, default=str)
    sys.stdout.write("\n")


def is_headless() -> bool:
    """Detect a machine with no browser (no DISPLAY and no BROWSER env)."""
    return not os.environ.get("DISPLAY") and not os.environ.get("BROWSER")
